# ---------- render.yaml ----------
# קובץ Blueprints לפריסה ברנדר
# שמור ברמת root של הריפו

databases:
  - name: wedding-db
    plan: free              # אם תרצה למנוע מחיקה אחרי 30 יום – שדרג ל-starter
    region: frankfurt
    postgresMajorVersion: 16

services:
  - type: web
    name: wedding-app
    runtime: docker         # Render יבנה את Dockerfile שלך כמו שהוא
    rootDir: .              # Dockerfile יושב ברוט-פרויקט
    region: frankfurt
    plan: free              # starter ($7) אם רוצים למנוע sleep
    autoDeploy: true        # build בכל push ל-main

    # משתנים שמוזרקים אוטומטית משאר השירותים:
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wedding-db
          property: connectionString

    # לא נוגעים ב-dockerCommand:
    # ה-CMD המקורי שנמצא בדוקרפייל (uvicorn …) ירוץ כרגיל
    #
    # thanks to python-dotenv --> load_dotenv("/etc/secrets/.env")
    # כל המשתנים שב-.env יהיו זמינים בזמן-ריצה.